# Generated by Django 5.2.6 on 2025-12-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=128)),
                ('dependencies', models.JSONField(blank=True, null=True)),
                ('file_stats', models.JSONField(blank=True, null=True)),
                ('project_size', models.BigIntegerField(blank=True, null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.CharField(max_length=512, unique=True)),
                ('cloud_provider', models.CharField(max_length=32)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockerfile', models.TextField(blank=True, null=True)),
                ('nginx_conf', models.TextField(blank=True, null=True)),
                ('docker_compose', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_files', to='analyzer.analysisresult')),
            ],
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('storage', models.FloatField()),
                ('model_version', models.CharField(default='v0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_prediction', to='analyzer.analysisresult')),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='project_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.projectrepo'),
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_score', models.IntegerField(default=0)),
                ('vulnerabilities', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_report', to='analyzer.analysisresult')),
            ],
        ),
    ]
